version: '3.9'

services:
  message_broker:
    build: 
      context: ./rabbitmq
      dockerfile: Dockerfile
    container_name: message_broker
    networks:
      - main-network
    # network_mode: host
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo:4.4.18
    # network_mode: host
    networks:
      - main-network
    env_file:
      - env/.db.env
    ports:
      - "27017:27017"
    volumes:
      # - mongo-data:/data/db
      - ./bootstrap/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mariadb:
    image: mariadb:latest
    networks:
      - main-network
    # network_mode: host
    ports:
      - "3306:3306"
    env_file:
      - env/.db.env
    volumes:
      # - mariadb-data:/var/lib/mysql
      - ./bootstrap/mariadb:/docker-entrypoint-initdb.d

  api_gateway:
    build: 
      context: .
      dockerfile: ./build/Dockerfile.api
    networks:
      - main-network
    container_name: api
    env_file:
      - env/.env
    ports:
      - "5000:5000"

  workers:
    build: 
      context: .
      dockerfile: ./build/Dockerfile.worker
    # network_mode: host
    networks:
      - main-network
    container_name: workers
    env_file:
      - env/.env

networks:
  main-network:

# volumes:
#   mongo-data:
#   mariadb-data: