version: '3.8'

services:
  mongodb:
    image: mongo:4.4.18
    network_mode: host
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./bootstrap/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mariadb:
    image: mariadb:latest
    network_mode: host
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./bootstrap/mariadb:/docker-entrypoint-initdb.d

volumes:
  mongo-data:
  mariadb-data: